language: node_js
node_js: "node"
services:
  - mongodb
env:
  - MONGODB_URI=mongodb://localhost:27017/devsign 
deploy:
  provider: heroku
  api_key:
    secure: qAHMIUWMEMqfSWwD7AwCSWFUhIIYlFnqqQPKV9rCPL0r4POW6pignRHg7qiQ6wG+NwDrH9+AYPE6aRpLvlqx8ydol7hDZv6UYWZeb/ysXzAYrNISPvdYuLkKW5b13FKVSsLJ5PGudeBICCXMyhAguw/0GohoqmVaSK6ujR+rcucn8VFU+Ah3Uz6s+Wmhd3gWx2cgcdyXwLODRjLWMFJmYP867tOvX6HKVL3dA8clbK5ruL5d4d8ezce3kKytTsxgWg47mEQPjkn1wC4Zp62zTk9MZ+5OA2R5mey1YPr3M4/42ZgBm4B6QUbQCliR5Bqb51rg++jj+Neh4tgUPEZKsYAXbczFDR+mPfu5r1FSljHrdBqUJGu+cBMs0hxtFvMUjYAIWdsKOyN2HdcDas9TL1xbfFfsf7gSZTJXDCdWHVdNlLKUL4j8213geeP8y8i6VNrnsQFrlM6hZgdSZm/6FeSkcJzaGZV1PBPYzIdeFs3fLaMkL+FeGrtpvMT8AH4mNH5sjtQ5z5XquqhAYyHz3LsNl5xpCW8hw2xgmqX2mzt8x+5fKSTMbgvAO7aYBSxixbaLyABbhxr1IsEKwDtu8kfwjsGOxr4FZXod24GAo55KQVcAyQxJkv4Aai1CJXRZouNO7wUj8eVU8FW+2CMomwg7Y61cG8wiKroakkqrQfs=
    app: twitterclonebe




